### ISSUE TITLE
Bot gets stuck in a code 401 loop

### ISSUE THREAD

**Issue by NanoCats** [mekb-turtle/pixel-canvas-bot#1]
Basically, the token expires or whatever and it stops working, I get a code 401, and the program appears trapped in a loop. I feel like it should be able to notice that it's failed its last ten attempts to place a pixel and should call it quits and display an error or something?

The log is huge and stuff but the important part looks to be

```
Error: Request failed with status code 401
    at createError (C:\Users\User\Desktop\pixel-canvas-bot-main\pixel-canvas-bot-main\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\User\Desktop\pixel-canvas-bot-main\pixel-canvas-bot-main\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\User\Desktop\pixel-canvas-bot-main\pixel-canvas-bot-main\node_modules\axios\lib\adapters\http.js:322:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
```

I thought that the firebase thing and or fingerprint might need to be updated, but I tried that and it didn't work. Waited a bit, tried again. eventually it worked, it should still probably stop and say "Hey! You need to update your firebase/fingerprint thing"

**Comment by sophuric** [comment]
yeah i was thinking about patching this, but i figured the user might be able to figure out what's wrong, stop it, and fix it themselves.
i'll just make it exit the program if we get an error instead.

**Comment by sophuric** [comment]
this will only loop if it returns a 412 now, any other error will exit
